version: '3.8'

services:
  # Auth Service and its DB
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - auth-db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_HOST=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=auth_db

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    networks:
      - app-network
    ports:
      - "5433:5432"

  # Patient Service and its DB
  patient-service:
    build:
      context: ./patient_services
    ports:
      - "5002:5002"
    networks:
      - app-network
    depends_on:
      - patient-db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_HOST=patient-db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=patient_db

  patient-db:
    image: postgres:16
    container_name: patient-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: patient_db
    networks:
      - app-network
    ports:
      - "5434:5432"

  # Admin Service and its DB
  admin-service:
    build:
      context: ./admin_services
    ports:
      - "5003:5003"
    networks:
      - app-network
    depends_on:
      - admin-db
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_HOST=admin-db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=admin_db

  admin-db:
    image: postgres:16
    container_name: admin-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: admin_db
    networks:
      - app-network
    ports:
      - "5435:5432"

  # Frontend Gateway
  frontend-gateway:
    build:
      context: ./frontend-gatway  # change to ./frontend-gateway if that's your actual folder name
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

networks:
  app-network:
    driver: bridge
