version: "3.9"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - auth-db

  auth-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_pg_data:/var/lib/postgresql/data

volumes:
  auth_pg_data:
